services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        deploy:
            replicas: 3        
        ports:
            - 8080:8080
        volumes:
            - "/home/vagrant/m3/web:/var/www/html:ro"
        networks:
            - homework
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        networks:
            - homework
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    homework:
